### ISSUE TITLE
trainer.validate

### ISSUE THREAD

**Issue by W55699** [graytowne/revisit_adv_rec#1]
I find some questions in the function of evaluate_epoch in the adv_trainer.py, which lose the function trainer.validation.Could you help me fix the problem?

**Comment by graytowne** [comment]
Closing the issue, should be fixed in #2 (though I still need more tests about the changes )

**Comment by W55699** [comment]
> 结束问题，应该[在#2](https://github.com/graytowne/revisit_adv_rec/pull/2)修复（虽然我仍然需要更多的测试的变化）

Thanks
