### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by ghost** [graytowne/revisit_adv_rec#3]
When the surrogate model is "sur_wmf_afs", the program reports the error of "RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation."
![image](https://user-images.githubusercontent.com/53649376/113556048-71fcff80-962e-11eb-832a-a198811ef6a2.png)

**Comment by graytowne** [comment]
Hi @zhudadi , thanks for reporting that issue. This is probably caused by the new version of PyTorch, which does not allowing modify variables that has `requires_grad=True`. I've fixed this in pull request #4 .
